### ISSUE TITLE
ReferenceError: Can't find variable: Notification

### ISSUE THREAD

**Issue by d3f113** [soundchaser128/clip-mash#61]
Hi,
after starting the container on docker, I got the error from the title on the starting page.
I run it on iPad.

**Comment by soundchaser128** [comment]
I'm guessing notifications are only available in secure contexts (https or localhost). Should be easy to fix.

**Comment by soundchaser128** [comment]
Should be fixed in 0.17.2,

**Comment by d3f113** [comment]
Works
